[workspace]
resolver = "3"
members = ["crates/nimbus-ipc", "crates/nimbusd", "crates/nimbus"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
license = "MIT"

[workspace.dependencies]
nimbus-ipc = { path = "crates/nimbus-ipc" }
nimbusd = { path = "crates/nimbusd" }
serde = { version = "1", features = ["derive"] }
toml = "1"
zbus = "5.19"
